# Generated by Django 4.2.27 on 2025-12-16 00:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('maths', 'Maths'), ('english', 'English'), ('science', 'Science')], max_length=20)),
                ('total_questions', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='At least one question is required.')])),
                ('correct_answers', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Correct answers cannot be negative.')])),
                ('score_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to='children.child')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='diagnostictest',
            constraint=models.CheckConstraint(check=models.Q(('correct_answers__lte', models.F('total_questions'))), name='diagnostic_test_correct_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='diagnostictest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('completed_at__isnull', True), ('is_completed', False)), models.Q(('completed_at__isnull', False), ('is_completed', True)), _connector='OR')), name='diagnostic_test_completion_consistency'),
        ),
    ]
