# Generated by Django 4.2.27 on 2025-12-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_diagnosticquestion_airequestlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='rank',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], help_text='Assigned once upon completion', max_length=10, null=True),
        ),
    ]
