# Generated by Django 4.2.27 on 2025-12-16 21:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


def _pg_column_type(cursor, *, table: str, column: str):
    cursor.execute(
        """
        SELECT data_type
        FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    row = cursor.fetchone()
    return row[0] if row else None


def _pg_constraint_exists(cursor, *, table: str, constraint_name: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = %s AND c.conname = %s
        """,
        [table, constraint_name],
    )
    return cursor.fetchone() is not None


def convert_bigint_pks_to_uuid(apps, schema_editor):
    """
    Safely migrates bigint primary keys to UUIDs on Postgres for early tables that
    were created with BigAutoField. This avoids Postgres failing with:
    "cannot cast type bigint to uuid" during AlterField.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

        # DiagnosticQuestion.id (bigint -> uuid) + dependent DiagnosticResponse.question_id.
        if _pg_column_type(cursor, table="assessments_diagnosticquestion", column="id") == "bigint":
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticquestion ADD COLUMN IF NOT EXISTS id_uuid uuid;"
            )
            schema_editor.execute(
                "UPDATE assessments_diagnosticquestion SET id_uuid = gen_random_uuid() WHERE id_uuid IS NULL;"
            )

            # Add new uuid FK column and backfill from mapping.
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticresponse ADD COLUMN IF NOT EXISTS question_uuid uuid;"
            )
            schema_editor.execute(
                """
                UPDATE assessments_diagnosticresponse r
                SET question_uuid = q.id_uuid
                FROM assessments_diagnosticquestion q
                WHERE q.id = r.question_id
                """
            )

            # Drop FK on old bigint column before replacing it.
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticresponse DROP CONSTRAINT IF EXISTS assessments_diagnosticresponse_question_id_fkey;"
            )

            # Replace question_id column with the uuid version.
            schema_editor.execute("ALTER TABLE assessments_diagnosticresponse DROP COLUMN question_id;")
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticresponse RENAME COLUMN question_uuid TO question_id;"
            )

            # Recreate unique constraint for (test_id, question_id) if it was dropped.
            unique_name = "assessments_diagnosticresponse_test_id_question_id_uniq"
            if not _pg_constraint_exists(cursor, table="assessments_diagnosticresponse", constraint_name=unique_name):
                schema_editor.execute(
                    f"ALTER TABLE assessments_diagnosticresponse ADD CONSTRAINT {unique_name} UNIQUE (test_id, question_id);"
                )

            # Swap primary key column on diagnosticquestion.
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticquestion DROP CONSTRAINT IF EXISTS assessments_diagnosticquestion_pkey;"
            )
            schema_editor.execute("ALTER TABLE assessments_diagnosticquestion DROP COLUMN id;")
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticquestion RENAME COLUMN id_uuid TO id;"
            )
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticquestion ADD PRIMARY KEY (id);"
            )

            # Re-add FK constraint to new UUID PK.
            schema_editor.execute(
                """
                ALTER TABLE assessments_diagnosticresponse
                ADD CONSTRAINT assessments_diagnosticresponse_question_id_fkey
                FOREIGN KEY (question_id)
                REFERENCES assessments_diagnosticquestion(id)
                DEFERRABLE INITIALLY DEFERRED;
                """
            )

        # DiagnosticResponse.id (bigint -> uuid)
        if _pg_column_type(cursor, table="assessments_diagnosticresponse", column="id") == "bigint":
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticresponse ADD COLUMN IF NOT EXISTS id_uuid uuid;"
            )
            schema_editor.execute(
                "UPDATE assessments_diagnosticresponse SET id_uuid = gen_random_uuid() WHERE id_uuid IS NULL;"
            )
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticresponse DROP CONSTRAINT IF EXISTS assessments_diagnosticresponse_pkey;"
            )
            schema_editor.execute("ALTER TABLE assessments_diagnosticresponse DROP COLUMN id;")
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticresponse RENAME COLUMN id_uuid TO id;"
            )
            schema_editor.execute(
                "ALTER TABLE assessments_diagnosticresponse ADD PRIMARY KEY (id);"
            )

        # AIRequestLog.id (bigint -> uuid)
        if _pg_column_type(cursor, table="assessments_airequestlog", column="id") == "bigint":
            schema_editor.execute(
                "ALTER TABLE assessments_airequestlog ADD COLUMN IF NOT EXISTS id_uuid uuid;"
            )
            schema_editor.execute(
                "UPDATE assessments_airequestlog SET id_uuid = gen_random_uuid() WHERE id_uuid IS NULL;"
            )
            schema_editor.execute(
                "ALTER TABLE assessments_airequestlog DROP CONSTRAINT IF EXISTS assessments_airequestlog_pkey;"
            )
            schema_editor.execute("ALTER TABLE assessments_airequestlog DROP COLUMN id;")
            schema_editor.execute(
                "ALTER TABLE assessments_airequestlog RENAME COLUMN id_uuid TO id;"
            )
            schema_editor.execute("ALTER TABLE assessments_airequestlog ADD PRIMARY KEY (id);")


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_diagnosticresponse'),
    ]

    operations = [
        migrations.RunPython(convert_bigint_pks_to_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='airequestlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diagnosticquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='diagnostictest',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='diagnosticquestion',
            name='diagnostic_question_unique_order',
        ),
        migrations.RemoveConstraint(
            model_name='diagnostictest',
            name='diagnostic_test_correct_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='diagnostictest',
            name='diagnostic_test_completion_consistency',
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='seed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.diagnostictest'),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_d',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='seed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticresponse',
            name='selected_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='rank',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='score_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('english', 'English'), ('science', 'Science')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticquestion',
            unique_together={('test', 'order')},
        ),
        migrations.RemoveField(
            model_name='diagnosticquestion',
            name='created_at',
        ),
    ]
