# Generated by Django 4.2.27 on 2025-12-16 21:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_diagnosticresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airequestlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diagnosticquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='diagnostictest',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='diagnosticquestion',
            name='diagnostic_question_unique_order',
        ),
        migrations.RemoveConstraint(
            model_name='diagnostictest',
            name='diagnostic_test_correct_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='diagnostictest',
            name='diagnostic_test_completion_consistency',
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='seed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.diagnostictest'),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='option_d',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticquestion',
            name='seed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosticresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticresponse',
            name='selected_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='rank',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='score_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('english', 'English'), ('science', 'Science')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='total_questions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticquestion',
            unique_together={('test', 'order')},
        ),
        migrations.RemoveField(
            model_name='diagnosticquestion',
            name='created_at',
        ),
    ]
